### ISSUE TITLE
support chinese

### ISSUE THREAD

**Issue by taojunnan** [leo-buneev/vuepress-plugin-fulltext-search#1]
great job
how can I search chinese

**Comment by WahaWaher** [comment]
\+ Non-latin characters in the query do not produce a result. In native search VuePress is [already  fixed](https://github.com/vuejs/vuepress/pull/2266/commits/b59288310a642497d4e954189922cc7393a3e1f0).

**Comment by leo-buneev** [comment]
Added some support for chinese and cyrillic characters in v2.0.2. It's not exactly trivial due to how flexsearch works, please let me know if there are issues.
