### ISSUE TITLE
Wrong category names for custom titles

### ISSUE THREAD

**Issue by merfire** [leo-buneev/vuepress-plugin-fulltext-search#21]
This is my sidebar config:
![sidebar](https://user-images.githubusercontent.com/21159950/94802505-1dab6580-03e8-11eb-91e3-0426e1ce31aa.png)

These are search results:
![screenshot](https://user-images.githubusercontent.com/21159950/94802641-53504e80-03e8-11eb-8253-b52003177840.png)

When I search for something in getting started category instead of showing title "Getting started" it shows route /getting-started/ as category name. (I understand that is shows the route because there isn't h1 in the markdown file)
I have same problem with custom children titles too, for example "Using ormconfig.json" isn't showing as my category name, instead it is showing "Using Configuration Sources" which is h1 in that markdown file.
Is there a way to show custom category names that we set in our config file, instead of only default h1 from markdown file?

**Comment by leo-buneev** [comment]
Fixed in 2.1.0, thanks for detailed description.

If page doesn't have it's own title, we attempt to take one from sidebar.

**Comment by DraCod** [comment]
Chinese not resolved，English is ok
