### ISSUE TITLE
Option to control default max number of returned search results

### ISSUE THREAD

**Issue by hamishwillee** [leo-buneev/vuepress-plugin-fulltext-search#28]
The default search system supplies 5 results by default. I actually prefer the way you do this, but I think people would prefer this configurable. 

Personally I'd prefer 10, with a link to launch page with all results if there are more :-)

**Comment by echojoshchen** [comment]
@hamishwillee It's not documented, but I found that you can use the built-in Vuepress setting `searchMaxSuggestions` in the theme config:

https://vuepress.vuejs.org/theme/default-theme-config.html#built-in-search

**Comment by hamishwillee** [comment]
Thanks @echojoshchen !
